### ISSUE TITLE
Problems with rlassoEffects

### ISSUE THREAD

**Issue by anzonyquispe** [maxhuppertz/hdmpy#1]
There is a problem with this function `res = jbl.Parallel(n_jobs=cores)(
            jbl.delayed(rlassoEffect_wrapper)` in line 504 of rlassoEffects.py. According to what I reviewed, I believe it is caused by `I3=np.delete(self.I3, i, axis=0)` this code tries to delete an element that by default is null *I3*. Do you have any idea Max how can I solve this problem?

**Comment by maxhuppertz** [comment]
Hi Anzony,

Thanks for bringing that up! I think I usually tried this with I3 not None. I changed the code so when I3 is None, it is now ignored. Let me know whether that works on your end!

**Comment by anzonyquispe** [comment]
Hi Max, 

I have tried again and I found the problem. I did not update the package. So sorry.
Thank you for your help.

Bests,

**Comment by maxhuppertz** [comment]
Oh no worries, I literally did that just now. Thanks for flagging that issue, let me know if/when you find more bugs!
